AllCops:
  TargetRubyVersion: 2.5
Metrics/LineLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Lint/RequireParentheses:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
